- hosts: all
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start httpd server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: h1.txt # We have define a html page 
        dest: /var/www/html/
